version: '3'

services:
  db:
    image: postgres:10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro

  bot:
    build: .
    command: npm run start-dev
    env_file: token.env
    volumes:
      - .:/usr/src/app:ro
      - /usr/src/app/node_modules
    depends_on:
      - db