version: '3'

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: telegram_upvoter
      POSTGRES_USER: telegram_upvoter
      POSTGRES_PASSWORD: securepassword
    volumes:
      - /var/lib/postgresql/data

  bot:
    build:
      context: .
      args:
        NODE_ENV: dev
    command: npm run start-dev
    env_file: token.env
    environment:
      LOG_LEVEL: debug
      POSTGRES_HOST: db
      POSTGRES_DB: telegram_upvoter
      POSTGRES_USER: telegram_upvoter
      POSTGRES_PASSWORD: securepassword
    volumes:
      - .:/usr/src
      - /usr/src/app/node_modules
    depends_on:
      - db
